### PR TITLE
Update installsh

### PR DESCRIPTION
**Pull request by keepittechie**
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

What does this implement/fix? Explain your changes.
---------------------------------------------------
The changes include:
- Removed redundant color definitions to reduce redundancy and improve readability.
- Combined package installation logic into a single function to avoid repetition and streamline the code.
- Added error handling to ensure the script exits gracefully on failures.
- Enhanced readability with consistent formatting, indentation, and added comments for better understanding.
- Improved user interaction by validating user input for yes/no questions and providing clearer instructions and feedback.
- Optimized function calls to avoid multiple calls to the same function.
- Redirected the output of package installations and other commands to /dev/null to hide the output for cleaner look.
…

Does this close any currently open issues?
------------------------------------------
Yes, my issue. I updated package list for apt. Replaced python => python3 & netcat => netcat-traditional
Packages removed from Kali Repository Causing Install Failure #33
…

Any relevant logs, error output, etc?
-------------------------------------
(If it’s long, please paste to https://gist.github.com/ and insert the link here.)
N/A
Any other comments?
-------------------
The script now checks for root permissions, installs necessary packages using different package managers, sets up the installation directory, and provides user interaction and feedback during the process.
…

Where has this been tested?
---------------------------
**Operating System:** … Kali Linux 2024.02, Fedora 34, Arch Linux

**Platform:** … VM's in Proxmox

**Target Platform:** … Linux systems with package managers apt, pacman, zypper, dnf, yum

### CODE REVIEW

**Comment by SofianeHamlaoui** [comment]
Hello @keepittechie, 

First thank you so much for checking this repo and trying to update it as it goes. 

The only issue with this is that the packages installation can take some time depending on the internet speed of the user, means if someone has a low internet speed he'll just wait without having any idea of the progress of the packages installation which can bother some of them. 

For everything else, it looks perfect and very good for me and ready to merge !

**Comment by keepittechie** [comment]
Hey @SofianeHamlaoui,

Your welcome!

I believe I came up with a fix for this. I'll work on it and commit within this branch before you merge.

**Comment by keepittechie** [comment]
@SofianeHamlaoui 

I updated install script to include progress bar and commit to this branch. Also tested again on the same OS's. Let me know if this cool.

**Comment by keepittechie** [comment]
@SofianeHamlaoui Do not merge yet, I forgot something. The progress bar is created using pv but if it's not installed it won't work. Let me create another function to check for pv and install if its not there.

**Comment by keepittechie** [comment]
@SofianeHamlaoui Clear to merge if you are happy with it. Thanks!

Added install_pv function:
- Checks if pv is installed. If not, attempts to install pv using the appropriate package manager.
- Calls install_pv at the start to ensure pv is available.
- If pv installation fails, the script will still attempt to proceed, and the progress bar functionality will be skipped.

**Comment by SofianeHamlaoui** [comment]
@keepittechie Perfect, I also thought about adding a progress bar. 

Still the issue is that your progress bar isn't really following the progress of the packages installation, here is an example : 

image

The progress bar takes 30 sec to finish as you configured it on the script but it'll keep being stuck like this at 100% till the installation is really finished, in this case it'll just make the same effect as waiting without even knowing if the installation really finished or the script got stuck...

**Comment by keepittechie** [comment]
@SofianeHamlaoui Give me a little time to think of another solution. I pulled this code for another script I wrote awhile ago and modified it to work here, but not well as you've shown. I'll come up with something else. Give me another day.

**Comment by keepittechie** [comment]
@SofianeHamlaoui I used a background job to monitor the progress of the install. I tested again. Let me know if this works for you.

**Comment by SofianeHamlaoui** [comment]
Looks good to me, I'll merge it now ! 

Thank you so much @keepittechie for your commits

**Pull request merged**
